# Generated by Django 3.2 on 2021-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('model_year', models.IntegerField()),
                ('Transmission', models.CharField(max_length=30)),
                ('Engine_size', models.IntegerField()),
                ('Fuel_type', models.CharField(max_length=30)),
                ('Drivetrain', models.IntegerField()),
                ('Lot_no', models.IntegerField()),
                ('Kilometer', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
